[build]
  functions = "netlify-functions"  # Directory where serverless functions are stored
  publish = "dist"                # Folder where static files are built

[functions]
  directory = "netlify-functions"
